# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20161218_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
