# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20161222_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
