# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20161222_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='fave',
            name='quote_author',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
